from .structures import OjtNjdFeature

class OpenJTalk:
    def __init__(
        self, dn_mecab: bytes = b"/usr/local/dic", userdic: bytes = b""
    ) -> None: ...
    def run_frontend(self, text: str) -> list[OjtNjdFeature]: ...
    def g2p(
        self, text: str, kana: bool = False, join: bool = True
    ) -> str | list[str]: ...

def mecab_dict_index(dn_mecab: bytes, path: bytes, out_path: bytes) -> int: ...
